require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.4
  Include:
    - ./**/*.rb
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/Guardfile'
  Exclude:
    - vendor/**/*
    - .vendor/**/*
    - pkg/**/*
    - spec/fixtures/**/*

# based on https://github.com/voxpupuli/modulesync_config/issues/168
Style/RegexpLiteral:
  EnforcedStyle: percent_r
  Enabled: true

# increase the limit a bit
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 12

# RSpec

# We don't use rspec in this way
RSpec/DescribeClass:
  Enabled: False

# Example length is not necessarily an indicator of code quality
RSpec/ExampleLength:
  Enabled: False
