development:
  :site_title: 'vhost-API'
  :api_modules:
    - 'domain'
    - 'email'
    - 'database'
    - 'vhost'
    - 'dns'
  :mail_home: 'testdata/vmail'
  :sieve_file: 'dovecot.sieve'

test:
  :site_title: 'vhost-API'
  :api_modules:
    - 'domain'
    - 'email'
    - 'database'
    - 'vhost'
    - 'dns'
  :mail_home: 'testdata/vmail'
  :sieve_file: 'dovecot.sieve'

production:
  :site_title: 'vhost-API'
  :api_modules:
    - 'domain'
    - 'email'
  :mail_home: '/var/vmail'
  :sieve_file: 'dovecot.sieve'
