# Settings for the production environment
production:
  # Select which API modules you want to enable.
  # Valid choices are:
  # 'domain', 'email', 'database', 'vhost', 'dns'
  # As of this version only 'domain' and 'email' are fully implemented.
  :api_modules:
    - 'domain'
    - 'email'

  # Mail storage location as defined by 'mail_home' in your dovecot.conf.
  :mail_home: '/var/vmail'

  # Sieve script filename as defined by 'sieve' in your dovecot.conf.
  :sieve_file: 'dovecot.sieve'

  # Globally allowed maximum filesize for the sieve script, regardless of
  # per-MailAccount quota settings.
  # Make sure to set the Webserve client request body max size to a higher
  # value to allow requests to receive a response from the API,
  # when it exceeds this limit only slightly.
  # Webserver limits are usually enforced by terminating the connection.
  :sieve_max_size: 1048576 # 1 MiB

  # Valid log_methods are:
  # 'internal' and 'syslog'
  :log_method: 'syslog'

  # Valid log_levels are:
  # 'DEBUG' < 'INFO' < 'WARN' < 'ERROR' < 'FATAL' < 'UNKNOWN'
  # Please note:
  # user actions (successful POST/PATCH/DELETE requests) will be logged as INFO
  :log_level: 'INFO'


# Settings for the test environment (used by rspec)
test:
  :api_modules:
    - 'domain'
    - 'email'
  :mail_home: 'testdata/vmail'
  :sieve_file: 'dovecot.sieve'
  :sieve_max_size: 1048576 # 1 MiB
  :log_method: 'internal'
  :log_level: 'ERROR'


# Settings for the development environment
development:
  :api_modules:
    - 'domain'
    - 'email'
    - 'database'
    - 'vhost'
    - 'dns'
  :mail_home: 'testdata/vmail'
  :sieve_file: 'dovecot.sieve'
  :sieve_max_size: 1048576 # 1 MiB
  :log_method: 'internal'
  :log_level: 'DEBUG'
