development:
  :db_adapter: mysql
  :db_host: localhost
  :db_user: foo
  :db_pass: bar
  :db_name: vhost_api

production:
  :db_adapter: postgres
  :db_encoding: unicode
  :db_host: db.example.com
  :db_user: foo
  :db_pass: bar
  :db_name: vhost_api
